import { StalkRecord } from './types';

// Five demo stalks covering all states
export const mockStalks: StalkRecord[] = [
  {
    id: 'stalk-001',
    userId: 'demo_user',
    request: {
      restaurantName: 'Indian Accent',
      city: 'New Delhi',
      date: '2026-06-14',
      guests: 2,
      preferredFrom: '20:00',
      preferredTo: '21:30',
    },
    restaurantId: 'rest-indian-accent',
    state: 'WATCHING',
    pollCount: 14,
    polls: [
      { polledAt: Date.now() - 3600000 * 4, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 3600000 * 3, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 3600000 * 2, slotsFound: ['7:45 PM'], newSlotDetected: false },
      { polledAt: Date.now() - 3600000, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 1800000, slotsFound: [], newSlotDetected: false },
    ],
    createdAt: Date.now() - 86400000 * 2,
    lastPolledAt: Date.now() - 1800000,
    slotFoundAt: null,
    foundSlot: null,
    bookingId: null,
    alternates: [
      {
        id: 'alt-001',
        name: 'Bukhara',
        cuisine: 'North Indian',
        priceRange: 4,
        rating: 4.7,
        bestAvailableSlot: '8:15 PM',
        matchScore: 88,
      },
      {
        id: 'alt-002',
        name: 'Dum Pukht',
        cuisine: 'Mughlai',
        priceRange: 4,
        rating: 4.5,
        bestAvailableSlot: '9:00 PM',
        matchScore: 72,
      },
      {
        id: 'alt-003',
        name: 'Masala Library',
        cuisine: 'Modern Indian',
        priceRange: 3,
        rating: 4.4,
        bestAvailableSlot: null,
        matchScore: 58,
      },
    ],
    expiresAt: Date.now() + 86400000 * 5,
  },
  {
    id: 'stalk-002',
    userId: 'demo_user',
    request: {
      restaurantName: 'Toit',
      city: 'Bengaluru',
      date: '2026-06-13',
      guests: 4,
      preferredFrom: '19:30',
      preferredTo: '21:00',
    },
    restaurantId: 'rest-toit',
    state: 'SLOT_FOUND',
    pollCount: 23,
    polls: [
      { polledAt: Date.now() - 7200000, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 5400000, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 3600000, slotsFound: ['7:45 PM'], newSlotDetected: true },
    ],
    createdAt: Date.now() - 86400000 * 3,
    lastPolledAt: Date.now() - 3600000,
    slotFoundAt: Date.now() - 3600000,
    foundSlot: '7:45 PM',
    bookingId: null,
    alternates: [
      {
        id: 'alt-004',
        name: 'The Biere Club',
        cuisine: 'Continental',
        priceRange: 3,
        rating: 4.3,
        bestAvailableSlot: '8:00 PM',
        matchScore: 65,
      },
      {
        id: 'alt-005',
        name: 'Windmills Craftworks',
        cuisine: 'Continental',
        priceRange: 3,
        rating: 4.2,
        bestAvailableSlot: '7:30 PM',
        matchScore: 61,
      },
      {
        id: 'alt-006',
        name: 'Arbor Brewing',
        cuisine: 'American',
        priceRange: 2,
        rating: 4.1,
        bestAvailableSlot: '8:30 PM',
        matchScore: 45,
      },
    ],
    expiresAt: Date.now() + 86400000 * 4,
  },
  {
    id: 'stalk-003',
    userId: 'demo_user',
    request: {
      restaurantName: 'Farmlore',
      city: 'Bengaluru',
      date: '2026-06-07',
      guests: 6,
      preferredFrom: '19:00',
      preferredTo: '20:30',
    },
    restaurantId: 'rest-farmlore',
    state: 'BOOKED',
    pollCount: 31,
    polls: [
      { polledAt: Date.now() - 86400000, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 43200000, slotsFound: ['7:00 PM'], newSlotDetected: true },
    ],
    createdAt: Date.now() - 86400000 * 5,
    lastPolledAt: Date.now() - 43200000,
    slotFoundAt: Date.now() - 43200000,
    foundSlot: '7:00 PM',
    bookingId: 'BKG-4821',
    alternates: [],
    expiresAt: Date.now() + 86400000 * 2,
  },
  {
    id: 'stalk-004',
    userId: 'demo_user',
    request: {
      restaurantName: 'Karavalli',
      city: 'Bengaluru',
      date: '2026-05-30',
      guests: 2,
      preferredFrom: '20:00',
      preferredTo: '21:30',
    },
    restaurantId: 'rest-karavalli',
    state: 'EXPIRED',
    pollCount: 48,
    polls: [
      { polledAt: Date.now() - 86400000 * 7, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 86400000 * 6, slotsFound: [], newSlotDetected: false },
    ],
    createdAt: Date.now() - 86400000 * 10,
    lastPolledAt: Date.now() - 86400000 * 3,
    slotFoundAt: null,
    foundSlot: null,
    bookingId: null,
    alternates: [
      {
        id: 'alt-007',
        name: 'Grasshopper',
        cuisine: 'South Indian',
        priceRange: 3,
        rating: 4.4,
        bestAvailableSlot: null,
        matchScore: 52,
      },
    ],
    expiresAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'stalk-005',
    userId: 'demo_user',
    request: {
      restaurantName: 'Trishna',
      city: 'Mumbai',
      date: '2026-06-20',
      guests: 3,
      preferredFrom: '19:00',
      preferredTo: '20:30',
    },
    restaurantId: 'rest-trishna',
    state: 'WATCHING',
    pollCount: 7,
    polls: [
      { polledAt: Date.now() - 7200000, slotsFound: [], newSlotDetected: false },
      { polledAt: Date.now() - 3600000, slotsFound: [], newSlotDetected: false },
    ],
    createdAt: Date.now() - 86400000,
    lastPolledAt: Date.now() - 3600000,
    slotFoundAt: null,
    foundSlot: null,
    bookingId: null,
    alternates: [
      {
        id: 'alt-008',
        name: 'Bastian',
        cuisine: 'Seafood',
        priceRange: 4,
        rating: 4.6,
        bestAvailableSlot: '7:30 PM',
        matchScore: 76,
      },
      {
        id: 'alt-009',
        name: 'Gajalee',
        cuisine: 'Seafood',
        priceRange: 2,
        rating: 4.3,
        bestAvailableSlot: '8:00 PM',
        matchScore: 63,
      },
      {
        id: 'alt-010',
        name: 'Mahesh Lunch Home',
        cuisine: 'Seafood',
        priceRange: 2,
        rating: 4.5,
        bestAvailableSlot: null,
        matchScore: 41,
      },
    ],
    expiresAt: Date.now() + 86400000 * 6,
  },
];
